services:
  - type: worker
    name: kitobijara-bot
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: REMINDERS_ENABLED
        value: "1"
      - key: PENALTY_PER_DAY_DEFAULT
        value: "2000"
